# Generated by Django 3.1.3 on 2021-01-06 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayName', models.CharField(max_length=50, verbose_name='Gateway Name')),
                ('gatewayEui', models.CharField(max_length=50, null=True, verbose_name='Gateway EUI')),
                ('gatewayDescription', models.CharField(max_length=100, verbose_name='Gateway Description')),
                ('typeofGateway', models.CharField(default='Indoor', max_length=50, null=True, verbose_name='Type of Gateway')),
                ('gatewayCreatedDate', models.TextField(null=True)),
                ('gatewayLatitude', models.FloatField(max_length=50, null=True, verbose_name='Gateway Latitude')),
                ('gatewayLongitude', models.FloatField(max_length=50, null=True, verbose_name='Gateway Longitude')),
                ('gatewayStatus', models.CharField(max_length=50, null=True, verbose_name='Gateway Status')),
                ('gatewayLastSeen', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
