# Generated by Django 3.1.3 on 2020-11-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enddevices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddevice',
            name='activation_method',
            field=models.CharField(blank=True, default='ABP', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enddevice',
            name='last_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enddevice',
            name='rssi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enddevice',
            name='snr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enddevice',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='description',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
